require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'test' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  if !ENV['CI']
    use_flipper!({ 'Flipper' => '0.80.0' })
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

    pod 'RNFileSelector', :path => '../node_modules/react-native-file-selector'

    pod 'RNFS', :path => '../node_modules/react-native-fs'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    post_install do |installer|
      flipper_post_install(installer)
    end
  end
end
